### PR TITLE
Fix os path compatibility

### LINKED ISSUE #56: [BUG] Windows style slashes don't work on mac
## Describe the bug

`\\` in TOML file specifying file locations don't work on Mac/UNIX.

```python 
 Exception: Emme project path does not exist /Users/elizabeth/Documents/urbanlabs/working/tm2py/examples/UnionCity/emme_project\mtc_emme.emp
```
## To Reproduce

- `test_union_city.py`

### Thoughts on resolution

Read in as a [`pathlib.Path` ](https://docs.python.org/3/library/pathlib.html)object

See discussion here: https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f

### Environment

Operating system: Mac-OS

### PR DESCRIPTION
**Pull request by e-lo**
## What existing problem does the pull request solve and why should we include it?

Filenames which use `\\` don't work on LINUX/Mac.  By using the built-in pathlib library functionality, we can read in POSIX-style path separators `/` and then it will work on either operating system.

## What is the testing plan?

*Demonstrate the code is solid by discussing how results are verified and covered by tests*

 - [x] Code for this PR is covered in tests 
 - [ ] Code passes all existing tests
    * NOTE: union_city tests is not passing currently - but wasn't passing before either.  

## Code formatting
*Code should be PEP8 compliant before merging by running a package like [`black`](https://pypi.org/project/black/)*

 - [x] Code linted

## Applicable Issues

Closes #56

### CODE REVIEW

**Comment by e-lo** [comment]
@i-am-sijia can you check that this branch works on windows and "review" the PR so I can merge it in?

**Comment by i-am-sijia** [comment]
- `test_docs.py` passes
image

- `test_config.py` has no response, seems stuck? I can leave it running to see if it gets somewhere.
image

- `test_tests.py` passes, but prints nothing.
image

- `test_tools.py` has no response.
image

- `test_union_city.py` has no response.
image

@e-lo

**Comment by e-lo** [comment]
@i-am-sijia can you run them all by just running the command pytest from
the tm2py folder? It should collect all the tests automagically (and if it
doesn't - we have a problem!)

**Comment by i-am-sijia** [comment]
@e-lo simply running `pytest` was actually the first thing I tried, but it stuck at running test_config.py, which was the first test `pytest` collects.  Then I ran the tests separately, which is my previous comment.

**Comment by i-am-sijia** [comment]
It might be something wrong with my EMME connection (to a license I'm sharing with others).  It says I'm connected but I can't open Emme Desktop.  Need to see what happened.

**Comment by e-lo** [comment]
Any update on if this is related to OS or other issues @i-am-sijia ?

**Comment by i-am-sijia** [comment]
Used the following steps to create tm2py env in conda (without Emme):

```
conda config --add channels conda-forge
conda create python=3.7 rtree geopandas folium osmnx -n <tm2py>
conda activate <tm2py>
git clone https://github.com/bayareametro/tm2py
cd tm2py
pip install -e .
```
All tests passed except `test_union_city.py`
image

**Pull request merged**
